### ISSUE TITLE
Issue on Configurable Product with multiple attribute 

### ISSUE THREAD

**Issue by rajesh0608** [develodesign/magento2-productdesignr#1]
Hi Folk,
As I am using this module for my project a configurable product with multiple attributes.

It's working for simple product only.

error is -

   Uncaught TypeError: Cannot read property 'options' of undefined
    at HTMLButtonElement.<anonymous> (box-3.html:1062)
    at HTMLButtonElement.dispatch (VM413 jquery.js:5226)
    at HTMLButtonElement.elemData.handle (VM413 jquery.js:4878)

**Comment by collymore** [comment]
Ok thanks, we can see it's only been used previously on configurable products with swatches and your example doesn't use that. We'll get a fixed added.

**Comment by collymore** [comment]
Hi,
It could be possible, there's an example here showing how to rotate objects on the canvas. 
http://jsfiddle.net/267qgp1t/
You would just need to rotate background image at the same time.
