### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by Apfelzimt** [develodesign/magento2-productdesignr#2]
Hi,
I just installed the plugin, it works fine, but if I refresh the site/once I've edited a product, I'm getting a JS error and the plugin doesn't work anymore.

Failed to load resource: the server responded with a status of 403 (Forbidden)
/pub/static/version1550698295/frontend/Theme/Name/en_US/Develodesign_Designer/js/dist/productdesigner.min.js:1

Uncaught Error: Script error for: Develodesign_Designer/js/dist/productdesigner.min
http://requirejs.org/docs/errors.html#scripterror
    at makeError (c9bb7df97d2fbb20521b1f1da2f46e02.js:166)
    at HTMLScriptElement.onScriptError (c9bb7df97d2fbb20521b1f1da2f46e02.js:1681)

Have you ever had this error?

**Comment by yaro-tr** [comment]
Check the file permissions.
Or simple do chmod 0777 -R path_to_your_bub_folder

**Comment by yaro-tr** [comment]
Pls, comment does you solve issue.

**Comment by Apfelzimt** [comment]
unfortunately I still have the same error

**Comment by Apfelzimt** [comment]
Hi, it is working now, my hosting fixed it. Somehow I didn't have enough user rights and the pub had to have 755 not 777.
Thanks!
