### ISSUE TITLE
Color view

### ISSUE THREAD

**Issue by Apfelzimt** [develodesign/magento2-productdesignr#3]
Hi,

I just checked the manual and would like to know how can I set up this view with the colors? I'd like to have the same view like in your tutorial

https://snag.gy/0JrGYz.jpg

Thanks

**Comment by yaro-tr** [comment]
Its standart magento 2 sample data products. In that example configurable product with size and colors. Size and color are swatches. Check this manual - https://docs.magento.com/m1/ce/user_guide/catalog/product-configurable-swatch.html 

Thanks.

**Comment by Apfelzimt** [comment]
thanks!
